import "./globals.css";
import { AuthProvider } from "./AuthProvider";

export const metadata = {
  title: "auth example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </AuthProvider>
  );
}
